import Navbar from './NavbarComponent/Navbar'
import Sidebar from './SidebarComponent/Sidebar'
import Footer from './FooterComponent/Footer'
import Header from './HeaderComponent/Header'
import Banners from './BannersComponent/Banners'
import FeatureBroducts from './FeaturedProductsComponent/FeatureBroducts'
import SingleProduct from './SingleProductComponent/SingleProduct'
import WhyChooseUs from './WhyChoosUsComponent/WhyChooseUs'
import TodayProducts from './TodayProductsComponent/TodayProducts'
import Subscripe from './SubscripeComponent/Subscripe'
import UnderConstyuction from './UnderConstructionComponent/UnderConstyuction'
import ApoutUs from './ApoutUSComponent/ApoutUs'
import Filters from './FiltersComponent/Filters'
import BreadCrumb from './BreadcrumbComponent/BreadCrumb'
import ProductsContainer from './ProductsContainer/ProductsContainer'
import ScrollToTop from './ScrollToTopRouter'
import ProductDetails from './ProductsDetailsComponent/ProductDetails'
import ProductDecAndReviewIndex from './ProductDescription&DetailsComponent/ProductDecAndReviewIndex'
import SelectedForU from './SelectedForUComponent/SelectedForU'
import CartComponent from './CartComponent/CartComponent'
import  CheckOut from '../components/CheckOutComponent/CheckOut'
import Loading from './LoadingComponent/Loading'

export {Loading,CheckOut,CartComponent,SelectedForU,ProductDecAndReviewIndex,ProductDetails,ScrollToTop,ProductsContainer,BreadCrumb,Filters,Navbar ,Sidebar ,Footer , Header,Banners , FeatureBroducts , SingleProduct , WhyChooseUs,TodayProducts , Subscripe , UnderConstyuction , ApoutUs} 